### ISSUE TITLE
Catch user creation errors and redirect with error flash 

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#88] opened 2017-05-06 07:34 UTC
Basically, prevent Christie from seeing the db error page when something goes wrong( something we expect, like using a duplicate email) and redirect to the same page with a flashed message explaining the reason for failing.

**Comment by alexander-bauer** [comment] 2017-05-06 22:15
I think this is more-or-less a duplicate of #49.

**Closed as completed by alexander-bauer** 2017-05-06 22:15 UTC
Labels: duplicate
