### ISSUE TITLE
Non registered email + password submission causes login error.

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#66] opened 2017-04-23 21:33 UTC

**Comment by Mjacks3** [comment] 2017-04-24 20:20
@alexander-bauer @ksilber1 @ichniow1 

I'm looking on this and I'm not able to reproduce this. Can you give me like a screenshot or a description of how you get this error?

**Comment by alexander-bauer** [comment] 2017-04-24 20:22
@Mjacks3 I'm not seeing it happen. The logs show an unsuccessful login attempt by an unknown email, which means it's failing down the right path.

**Comment by alexander-bauer** [comment] 2017-04-25 21:34
@Mjacks3 Since we can't reproduce this, I'm going to close it. If it's still an issue, definitely re-open it.

**Closed as completed by alexander-bauer** 2017-04-25 21:34 UTC
Labels: invalid, webapp logic
