### ISSUE TITLE
User creation errors cause server exception

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#37] opened 2017-04-12 22:21 UTC
For example, creating a user which shares an email with an existing user will raise `sqlalchemy.exc.IntegrityError`, and creating a user with an empty password will raise `builtins.ValueError`.

**Comment by Mjacks3** [comment] 2017-04-17 01:14
@alexander-bauer  is this still an issue? I can't replicate it. 
 If so I may need to switch over to a linux dev env.

**Comment by alexander-bauer** [comment] 2017-04-17 01:15
@Mjacks3 I'll test in a moment, but if you need a Linux dev environment, you can use the demo site.

**Comment by Mjacks3** [comment] 2017-04-19 18:04
duplicate of #49

**Closed as completed by Mjacks3** 2017-04-19 18:04 UTC
Labels: bug, duplicate, webapp logic
